# Generated by Django 5.2.17 on 2026-09-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xss_lab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoredComment',
        ),
    ]
